FROM node:22-bookworm

RUN apt-get update && apt-get install -y sudo socat jq && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash linuxbrew && \
    echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"

RUN brew install Hyaxia/tap/blogwatcher && \
	brew install uv

USER root

# Install chrome
    # Download and install Google Chrome
RUN apt-get update && \
    curl -L -o /tmp/google-chrome-stable_current_amd64.deb \
        https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y --fix-broken /tmp/google-chrome-stable_current_amd64.deb && \
    # Clean up
    rm -f /tmp/google-chrome-stable_current_amd64.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Example binary 1: Gmail CLI
RUN curl -L https://github.com/steipete/gogcli/releases/download/v0.6.1/gogcli_0.6.1_linux_amd64.tar.gz \
  | tar -xz -C /usr/local/bin && chmod +x /usr/local/bin/gog

# Add more binaries below using the same pattern

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY ui/package.json ./ui/package.json
COPY scripts ./scripts

RUN corepack enable
RUN pnpm install --frozen-lockfile

COPY . .

RUN sed -i 's/antigravity\/1.11.5/antigravity\/1.15.8/g' node_modules/@mariozechner/pi-ai/dist/providers/google-gemini-cli.js

RUN CLAWDBOT_A2UI_SKIP_MISSING=1 pnpm build
ENV CLAWDBOT_PREFER_PNPM=1
RUN pnpm ui:install
RUN pnpm ui:build
RUN npm i -g clawdhub undici

# Install skills in the container itself
#RUN clawdhub install self-improving-agent

ENV NODE_ENV=production

CMD ["node","dist/index.js"]
